### ISSUE TITLE
bug: outline() and sprite() don't seem to work with each other

### ISSUE THREAD

**Issue by dragoncoder047** [kaplayjs/kaplay#394]
I want to outline a sprite  when it is being hovered on by the mouse so I added the outline component... it doesn't seem to work.

example:

```js
kaplay();

loadBean();

add([
    sprite("bean"),
    // rect(64, 64),
    // color(BLACK),
    pos(100, 100),
    outline(5, WHITE),
]);
```

is it possible to add an outline to a sprite or is there another way to do it?

If outline is supposed to work with sprite just fine, this is a bug. If it is already working as intended, I think it should be noted in the docs that outline doesn't display on sprites.

**Comment by mflerackers** [comment]
Outline doesn't work because it is actually forwarded to the drawing operation.
If you make an object with a rect component and an outline component, the outline component adds outline settings to the object. The rect component passes these settings to drawRect() when drawing. All primitives do this.
But sprite and uvquad, even if they pass these options to drawSprite and drawUVQuad, won't get the same effect since these routines don't draw outlines.
Also, users would probably expect a nice outline, following the alpha of the sprite, not a rectangle. It's easy to do with a shader, but switching shaders hurts performance. So currently it is unsupported.

**Comment by mflerackers** [comment]
In the shaders section of our discord are a few shaders which can be used to add outlines to sprites.

**Comment by dragoncoder047** [comment]
> In the shaders section of our discord are a few shaders which can be used to add outlines to sprites.

sorry I don't have a discord account, can you post one?

**Comment by mflerackers** [comment]
This is a one pixel outline. Note that the example sprites aren't the best choice to show the outline, because they don't have any padding and thus can't have a complete outline.

```glsl
uniform vec3 u_color;

vec4 frag(vec2 pos, vec2 uv, vec4 color, sampler2D tex) {
    vec4 outlineColor = vec4(vec3(u_color) / 255.0, 1.0);
    vec2 textureSize = vec2(2048, 2048);
    vec4 pixel = texture2D(tex, uv);
    const float EPSILON = 0.0001;
    if(pixel.a < EPSILON)
    {
        vec2 offset = vec2(1.0 / textureSize.x, 0.0);
        float left = texture2D(tex, uv - offset).a;
        float right = texture2D(tex, uv + offset).a;
     
        offset.x = 0.0;
        offset.y = 1.0 / textureSize.y;
        float up = texture2D(tex, uv - offset).a;
        float down = texture2D(tex, uv + offset).a;
     
        float a = step(EPSILON, left + right + up + down);
        pixel = mix(pixel, outlineColor, a);
    }
    return pixel;
}
```

https://kaboomjs.com/play?example=shader&code=eJyVU8GO0zAQPddfMcrJVk2aTbOoIiwHaA9IK0BUnBBivY3TRqRxFDtLu6v%2BO%2BPYKWm7l%2FpgTSbvzXu2Z%2F6IR6W2lBFSKpEt66YwkgaPUlQBh2Ciu4Se2ERYV%2BuAneDWG6XN%2FgTpUh7rwBuRyYYGqjVlUUlEV21ZcnggbVXkqtnCk1xNof29UqVqUrJSlTaQI9XA4tvy8%2F3XL3AHURhF0U1KCIITyBuxphjFUCvNoYvapy5IoKvDQYttXcomnoOROwYvBHB1AO%2Fkk8VhaZuzxabUe2Awgfj2Now43IQRS3tmbCuZtpHL4lk6YkzjKJlxsPt%2FYAJ1sZMlQjwhnlOMOHr0oCKnHSQU8L4%2FJev%2BOJ9HRZXnWppeDO2gt4GLEItGR492uYsrZW5ek4c3viILxTmnKdab10njC9KR6n6EO%2FdE6Xl%2Bj%2FlL0%2Ftz6ba%2B1mym%2FlbXenVMgTRtZE39tXN3WWN%2F%2FrE1M%2B7qD261f89tsXMPx0%2B6iIPw4EO3NxJdVY6VkgN5wFkQWUZ%2FkpEezhjjZIQdTGfYaklkv%2FRKlJLOuvBicCiDuw9AX8hoFPheDd7Bx%2FsfC4QfGJJ%2BXQr5Ie2lplYrHoq9vUbs%2B2I%2B0PoH%2FN439A%3D%3D

**Comment by mflerackers** [comment]
This one has thickness, and can be both inside or outside.

```glsl
uniform vec3 u_color;
uniform float u_inside;
uniform float u_thickness;
const float EPSILON = 0.0001;
const int MAX_THICKNESS = 10;

vec4 frag(vec2 pos, vec2 uv, vec4 color, sampler2D tex) {
    vec4 outlineColor = vec4(vec3(u_color) / 255.0, 1.0);
    vec2 textureSize = vec2(2048, 2048);
    vec4 pixel = texture2D(tex, uv);
    int thickness = int(u_thickness);
    bool outside = u_inside == 0.0;
    if((pixel.a < EPSILON) == outside)
    {
        float total = 0.0;
        vec2 d = vec2(1.0 / textureSize.x, 1.0 / textureSize.y);
        for (int i = 1; i <= MAX_THICKNESS; i++) {
            if (i > thickness) { break; }
            vec2 offset = vec2(d.x * float(i), 0.0);
            total += texture2D(tex, uv - offset).a;
            total += texture2D(tex, uv + offset).a;
        
            offset.x = 0.0;
            offset.y = d.y * float(i);
            total += texture2D(tex, uv - offset).a;
            total += texture2D(tex, uv + offset).a;
        }
        float a = outside ? step(EPSILON, total) :
            1.0 - step(4.0 * u_thickness, total);

        pixel = mix(pixel, outlineColor, a);
    }
    return pixel;
}
```

https://kaplay.lajbel.com/?code=eJy9VtuSqsgSfW6%2FgugnHJ0WUFB3T89EyUXBBgUExRMTMyAlolzkJujE%2FvcpWu3uvWfHxDkvpx4wycpM1lqVWeHBduI4xJuNRhDbrn5M%2FRzijwc7f2xjj66d21%2F80PZg5xh5z46dQabX9s3RTCuJ6diLAVqKbux4w0MWR9TvDAus%2Bpdbk4JWG2Cl6BohgjTrbRgVvWeapPGCYYsTNxySCrjwctWlIu4AolgeGpwiCmMRzEq2lFF5Aqjr0VAKZioHgUBO3TR19hfyYpx6Ou%2FOI4Yy%2Br7O9LiuxBX9im7ZlDmjW3Jpieacbs1UxQGyvmSjcRibcG8DIbVjdk%2Bar6Vdljv7GIvF0jvC2dDhtqst3YGnogfT%2FtnN%2BywYrS092V42js%2B%2B7oyKHRrj3SgCPBHApZiMhhM117gRTdNJOLGC1dSidDXeDi%2B5KeWsti%2B1yhS9nXuenpU80PL96EzY%2BvgCJq3WqbefzhdMJ8lsUK7mSBg2JTphTKUWUQqSmsR9HozKgbSamoGQlGcwjQ8bFew6VMGEBhC3up5NFKnsDhJhlIBRMZAgGx%2FnktXPFHYTeDpMPGeuenOxXKyAEQ97e35PqvZKTHwiBZWVTipB6HLFaCbAJSfr57PAncdHnxOS5Y6MaSe3NmtfKpKY0bwLPC57s9Y2pTXKZo4M5Z1kb9ldLjv7VstJB9BeVMM4Ti2whCC8LJd9W4ELUoH2iaUjXRPWvu5S9F5M%2BIBD2OOxZ%2FbDcO6SBa9koOMqarUg%2BfV2TFbTbNBlKOJiiQAsSHn36o21QA4t1feJPJnJ3opC%2BumET5gVJZ1nI3kIRXkrtmDpOqLWlbamMurNl4tkvj1Oz4yHem%2FBdvrw5LVOjnoYuxdFNXJiMOQsayOarmL1HX6YMEU0oYeuEROpM%2FHlglQzmWxFBOW%2BavTcISYsYKds7E9Fl8pplvSBZ1D5fG14objOyr06u0zkYB%2Fpg86ucF%2B5ZalkqDSVSa1hKZ5aMAM%2BMyCnh6qYcWMDAOLsZZaYO7ty6JjxPlUiyYeoH4CcLdeakNP28AQ23EBhzP5hujP7y3UWVZUKDjkFZr11SieD8nyWJ64XAuG0WquZr5mOupL0ZG8CUuoXZ32aCgtzUk1kbs2qOa%2BHl0ScxMWZUeQ945uXlQXSvvBaruTJylOymT63eJEJdokXkJ1%2BB4zdIy1WPnk0wrIe6JGkGTSfHiTP815eHu%2BXx852YYo%2FxkUe%2BBFEF0hUBEEb%2B7NRRP42TkPsBDddrPhjEwdx%2Bvzu3aLkHLn9KPNd%2BE9%2FvvM3hwhm2XNjE0dZftvg57r4OlOwF4x4IgiCvO%2F6UY7JYPXHYiKyU4XXdRRBEs%2BNBvp6D9umtocji8KOcdbG3qzi9Gb0sDdgbSyzw2MAU4rDclg1sb8aGFpvATdqbB2Hyta%2BulgXv5FqYh2Mouknoo2RT0Tz%2BZ5J1ZXyIoW6f4HXRAqniN6gjdXPj8AedvQrGKCQWwLF4chqI4wo6KHm9i4HCkLv%2BCeB6hB0nQc1zlpLFHGXFXt50%2Bn6IX%2BL42%2FfebKxX%2B5CNuuQW2LzLexKvF5XxfM4twPsU513du6dE2KNJPhE9ql6k%2BI757n5UQCdNYbXxPz6oJ7Rzy8v3x4g8rVa9Tk8PDz4WxSM%2FfqhAvJjTgrtwzP29b3mO7B4u81gfkfnPlXYT1cyuN9s10Q%2BAanXlWLrB%2FJjP9%2BKNZ%2Fs%2Fzqn9aOcb5Kv%2BwjXd7J%2B2jujPRc9P5D%2F%2FzF%2F%2Fa4VbOy9V7DfsCyHR%2FzWRu1r7Sb2pT6u%2Buh%2Fvu73kPnT53G%2BR6LRvBe%2FN3%2FoV9cGbX8zcm3MvnG%2F4kkhwh5ds54bXxt%2FopvIdl38P42H7NM%2FmWa78YCmHR%2BgsewR9Vu2sQOID97Mf9xaOJqEXzG8brfH21w%2FfsFGrwbfvrquE4V8xM3xTgn5yMbD1yYq%2FPu%2FY%2BnWYKjPaJj%2FBY3Gc9%2BDIX8ApvsB5m%2BqGvxn

**Comment by mflerackers** [comment]
Since a shader can only draw within the quad of the sprite, you can't draw an outline outside the quad.
